version: "3"

services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  user_service:
    image: user_service
    tty: true
    command: bash -c "alembic upgrade head && uvicorn service.app:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      postgresdb:
        condition: service_healthy
    env_file:
      - .env


volumes:
  pg_data: