"""CreateDatabase

Revision ID: e6c33b9ae832
Revises: fc6ffcebc6e7
Create Date: 2023-12-02 20:18:43.404092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c33b9ae832'
down_revision: Union[str, None] = 'fc6ffcebc6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
